from __future__ import annotations

import html
import zipfile
from datetime import UTC, datetime
from pathlib import Path

from local_meetscribe.schemas import Exports, Transcript
from local_meetscribe.utils.time import format_hhmmss, format_srt_timestamp, format_timestamp


def write_exports(transcript: Transcript, output_dir: Path) -> Transcript:
    output_dir.mkdir(parents=True, exist_ok=True)
    updated = transcript.model_copy(deep=True)
    json_path = output_dir / "transcript.json"
    md_path = output_dir / "transcript.md"
    txt_path = output_dir / "transcript.txt"
    srt_path = output_dir / "transcript.srt"
    vtt_path = output_dir / "transcript.vtt"
    docx_path = output_dir / "transcript.docx"
    minutes_path = output_dir / "meeting_minutes.md"

    updated.exports = Exports()
    json_path.write_text(updated.model_dump_json(indent=2, by_alias=True), encoding="utf-8")
    md_path.write_text(render_markdown(updated), encoding="utf-8")
    txt_path.write_text(render_txt(updated), encoding="utf-8")
    srt_path.write_text(render_srt(updated), encoding="utf-8")
    vtt_path.write_text(render_vtt(updated), encoding="utf-8")
    minutes_path.write_text(render_minutes(updated), encoding="utf-8")
    write_docx(updated, docx_path)

    updated.exports = Exports(
        **{
            "json": str(json_path.resolve()),
            "md": str(md_path.resolve()),
            "txt": str(txt_path.resolve()),
            "srt": str(srt_path.resolve()),
            "vtt": str(vtt_path.resolve()),
            "docx": str(docx_path.resolve()),
            "minutes_md": str(minutes_path.resolve()),
        }
    )
    json_path.write_text(updated.model_dump_json(indent=2, by_alias=True), encoding="utf-8")
    return updated


def render_markdown(transcript: Transcript) -> str:
    lines = [
        "# Transcript",
        "",
        f"Source: {transcript.source.filename}",
        f"Duration: {format_hhmmss(transcript.source.duration_sec)}",
        f"Engine: {transcript.config.asr_engine} / {transcript.config.asr_model}",
        f"Created: {transcript.created_at.isoformat()}",
        "",
    ]
    for segment in transcript.segments:
        lines.append(
            f"[{format_timestamp(segment.start)} - {format_timestamp(segment.end)}] "
            f"{segment.speaker}: {segment.text_clean}"
        )
    lines.append("")
    return "\n".join(lines)


def render_txt(transcript: Transcript) -> str:
    return (
        "\n".join(f"{segment.speaker}: {segment.text_clean}" for segment in transcript.segments)
        + "\n"
    )


def render_srt(transcript: Transcript) -> str:
    blocks: list[str] = []
    for index, segment in enumerate(transcript.segments, start=1):
        time_range = (
            f"{format_srt_timestamp(segment.start)} --> {format_srt_timestamp(segment.end)}"
        )
        blocks.append(
            "\n".join(
                [
                    str(index),
                    time_range,
                    f"{segment.speaker}: {segment.text_clean}",
                ]
            )
        )
    return "\n\n".join(blocks) + "\n"


def render_vtt(transcript: Transcript) -> str:
    blocks = ["WEBVTT", ""]
    for segment in transcript.segments:
        blocks.extend(
            [
                f"{format_timestamp(segment.start)} --> {format_timestamp(segment.end)}",
                f"{segment.speaker}: {segment.text_clean}",
                "",
            ]
        )
    return "\n".join(blocks)


def render_minutes(transcript: Transcript) -> str:
    return "\n".join(
        [
            "# Meeting Minutes",
            "",
            "_Derived summary. Not generated by default; enable a local LLM minutes "
            "engine to fill this._",
            "",
            "## Summary",
            "",
            "## Decisions",
            "",
            "## Action Items",
            "- [ ] Owner - task - due date if mentioned",
            "",
            "## Open Questions",
            "",
            "## Risks / Follow-ups",
            "",
            f"Generated locally from transcript job `{transcript.id}` at "
            f"{datetime.now(UTC).isoformat()}.",
            "",
        ]
    )


def write_docx(transcript: Transcript, path: Path) -> None:
    document_xml = _document_xml(transcript)
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as docx:
        docx.writestr(
            "[Content_Types].xml",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels"
    ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml"
    ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>""",
        )
        docx.writestr(
            "_rels/.rels",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
    Target="word/document.xml"/>
</Relationships>""",
        )
        docx.writestr("word/document.xml", document_xml)


def _document_xml(transcript: Transcript) -> str:
    paragraphs = [
        _paragraph("Transcript", style="Title"),
        _paragraph(f"Source: {transcript.source.filename}"),
        _paragraph(f"Duration: {format_hhmmss(transcript.source.duration_sec)}"),
        _paragraph(f"Engine: {transcript.config.asr_engine} / {transcript.config.asr_model}"),
    ]
    for segment in transcript.segments:
        paragraphs.append(
            _paragraph(
                f"[{format_timestamp(segment.start)} - {format_timestamp(segment.end)}] "
                f"{segment.speaker}: {segment.text_clean}"
            )
        )
    return (
        """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>"""
        + "".join(paragraphs)
        + """
    <w:sectPr/>
  </w:body>
</w:document>"""
    )


def _paragraph(text: str, *, style: str | None = None) -> str:
    style_xml = ""
    if style:
        style_xml = f'<w:pPr><w:pStyle w:val="{html.escape(style)}"/></w:pPr>'
    return f"<w:p>{style_xml}<w:r><w:t>{html.escape(text)}</w:t></w:r></w:p>"
